apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-neteye
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/commexcom/monitor-neteye.git
    targetRevision: feat/database-devops
    path: devops
    kustomize:
      namePrefix: 'monitor-neteye-'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
