apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/commexcom/monitor-neteye.git
    targetRevision: { { branch } }
    path: devops/database
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor-neteye
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
