{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
spec:
  project: default
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision | default "main" }}
    path: {{ .path }}
    {{- if .values }}
    helm:
      values: |
        {{- toYaml .values | nindent 8 }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
{{- end }}