applications:
  - name: monitor-neteye-api
    repoURL: https://github.com/commexcom/monitor-neteye.git
    targetRevision: HEAD
    path: devops/api
    namespace: monitor-neteye
    values:
      repositoryName: monitor-neteye-api
      repositoryOwner: athaydaooo
      imageTag: latest
      replicaCount: 3
      service:
        enabled: true
        type: ClusterIP
        internalPort: 3000
        externalPort: 443
      ingress:
        enabled: true
        className: 'nginx'
        annotations:
          {
            nginx.ingress.kubernetes.io/ssl-redirect: 'true',
            nginx.ingress.kubernetes.io/force-ssl-redirect: 'true',
            nginx.ingress.kubernetes.io/rewrite-target: /,
          }
        hosts:
          - host: subdomain.domain.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - subdomain.domain.com
            secretName: domain-tls

  - name: monitor-neteye-database
    repoURL: https://github.com/commexcom/monitor-neteye.git
    targetRevision: HEAD
    path: devops/database
    namespace: monitor-neteye
